version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_DATABASE: chitchat
      MYSQL_PASSWORD: mysql
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - data-volume:/var/lib/mysql
volumes:
  data-volume:
